export const gameState = {
    minerals: 500,
    vespene: 250,
    supplyUsed: 0,
    supplyCap: 10,
    unitCounts: {
        scv: 0,
        scv_mark_2: 0,
    },
    upgrades: {
        infantryWeapons: 0,
        infantryArmor: 0,
        stimpack: false,
        u238shells: false,
        siegeModeResearched: false,
        charonBoosters: false,
        empShockwave: false,
    },
    academyBuilt: false,
    engineeringBayBuilt: false,
    armoryBuilt: false,
    barracksBuilt: false,
    factoryBuilt: false,
    starportBuilt: false,
    scienceFacilityBuilt: false,
    physicsLabBuilt: false,
    controlTowerBuilt: false,
    covertOpsBuilt: false,
    comsatStationBuilt: false,
    nuclearSiloBuilt: false,
};